import "./globals.css";
import "../assets/css/styles.css";
import "../assets/css/custom.css";

import { Inter } from "next/font/google";
import Emitter from "semitter";

const inter = Inter({ subsets: ["latin"] });

let emitter = new Emitter();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export { emitter };
